"""Added description to AssetLocation

Revision ID: 2b2deb332e0e
Revises: 13b32a084db8
Create Date: 2023-06-23 16:43:04.205965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2deb332e0e'
down_revision = '13b32a084db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_location', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
