"""added asset table

Revision ID: 54b4264464fa
Revises: 093eda559f73
Create Date: 2023-06-02 18:45:25.615740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b4264464fa'
down_revision = '093eda559f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_code_id', sa.Integer(), nullable=False),
    sa.Column('location_code_id', sa.Integer(), nullable=False),
    sa.Column('process_code_id', sa.Integer(), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('asset_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['location_code_id'], ['location_code.id'], ),
    sa.ForeignKeyConstraint(['process_code_id'], ['process_code.id'], ),
    sa.ForeignKeyConstraint(['service_code_id'], ['service_code.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('asset')
    # ### end Alembic commands ###
