"""local number

Revision ID: 924872770e3f
Revises: cc50a8da7c65
Create Date: 2023-06-16 00:21:09.942282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924872770e3f'
down_revision = 'cc50a8da7c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('local_number')

    # ### end Alembic commands ###
