"""removed service code

Revision ID: bee1e8ac6d74
Revises: c11eeb8fd0d6
Create Date: 2023-06-22 02:04:27.017734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee1e8ac6d74'
down_revision = 'c11eeb8fd0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_constraint('asset_service_code_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_code_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_code_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('asset_service_code_id_fkey', 'service_code', ['service_code_id'], ['id'])

    # ### end Alembic commands ###
