"""duplicate status

Revision ID: c11eeb8fd0d6
Revises: 924872770e3f
Create Date: 2023-06-22 01:59:47.751728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11eeb8fd0d6'
down_revision = '924872770e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_status', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('duplicate_status')

    # ### end Alembic commands ###
